#https://docs.projectcalico.org/v3.1/getting-started/kubernetes/tutorials/stars-policy/manifests/02-backend.yaml

kind: Namespace
apiVersion: v1
metadata:
  name: pci
---
apiVersion: v1
kind: Service
metadata:
  name: payments 
  namespace: pci
spec:
  ports:
  - port: 6380
    targetPort: 6380 
  selector:
    role: payments 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: payments 
  namespace: pci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: payments 
    spec:
      containers:
      - name: payments 
        image: calico/star-probe:v0.1.0
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=6380
        - --urls=http://frontend.stars:80/status,http://payments.pci:6380/status,http://backend.stars:6379/status,http://client.client:9000/status,http://queue.infrastructure:5000/status
        ports:
        - containerPort: 6380