# https://docs.projectcalico.org/v3.1/getting-started/kubernetes/tutorials/advanced-policy

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: pci
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
